# Task identifier
task: 1

# Model architecture
pretrained_model: symanto/xlm-roberta-base-snli-mnli-anli-xnli
drop_prob: 0.1
max_seq_len: 512

# Hyperparameters
batch_size: 16
accum_steps: 8
learning_rate: 5e-5
num_epochs: 5
num_workers: 4

# Seed
seed: 0

# Path
model_path: ''
output_path: ''
models_dir: ./models